try:
	from QAbstractAnimation import QAbstractAnimation
	from QAbstractEventDispatcher import QAbstractEventDispatcher
	from QAbstractFileEngine import QAbstractFileEngine
	from QAbstractFileEngineIterator import QAbstractFileEngineIterator
	from QAbstractItemModel import QAbstractItemModel
	from QAbstractState import QAbstractState
	from QAbstractTransition import QAbstractTransition
	from QAnimationGroup import QAnimationGroup
	from QBasicTimer import QBasicTimer
	from QBitArray import QBitArray
	from QBuffer import QBuffer
	from QByteArray import QByteArray
	from QByteArrayMatcher import QByteArrayMatcher
	from QChildEvent import QChildEvent
	from QCoreApplication import QCoreApplication
	from QCryptographicHash import QCryptographicHash
	from QDataStream import QDataStream
	from QDate import QDate
	from QDateTime import QDateTime
	from QDir import QDir
	from QDirIterator import QDirIterator
	from QDynamicPropertyChangeEvent import QDynamicPropertyChangeEvent
	from QEasingCurve import QEasingCurve
	from QElapsedTimer import QElapsedTimer
	from QEvent import QEvent
	from QEventLoop import QEventLoop
	from QEventTransition import QEventTransition
	from QFile import QFile
	from QFileInfo import QFileInfo
	from QFileSystemWatcher import QFileSystemWatcher
	from QFSFileEngine import QFSFileEngine
	from QGenericArgument import QGenericArgument
	from QHistoryState import QHistoryState
	from QIODevice import QIODevice
	from QLibraryInfo import QLibraryInfo
	from QLine import QLine
	from QLineF import QLineF
	from QLocale import QLocale
	from QMargins import QMargins
	from QMetaClassInfo import QMetaClassInfo
	from QMetaEnum import QMetaEnum
	from QMetaMethod import QMetaMethod
	from QMetaObject import QMetaObject
	from QMetaProperty import QMetaProperty
	from QMimeData import QMimeData
	from QModelIndex import QModelIndex
	from QMutex import QMutex
	from QMutexLocker import QMutexLocker
	from QObject import QObject
	from QPauseAnimation import QPauseAnimation
	from QPersistentModelIndex import QPersistentModelIndex
	from QPluginLoader import QPluginLoader
	from QPoint import QPoint
	from QPointF import QPointF
	from QProcess import QProcess
	from QProcessEnvironment import QProcessEnvironment
	from QPropertyAnimation import QPropertyAnimation
	from QReadLocker import QReadLocker
	from QReadWriteLock import QReadWriteLock
	from QRect import QRect
	from QRectF import QRectF
	from QRegExp import QRegExp
	from QResource import QResource
	from QRunnable import QRunnable
	from QSemaphore import QSemaphore
	from QSequentialAnimationGroup import QSequentialAnimationGroup
	from QSettings import QSettings
	from QSignalMapper import QSignalMapper
	from QSignalTransition import QSignalTransition
	from QSize import QSize
	from QSizeF import QSizeF
	from QSocketNotifier import QSocketNotifier
	from QState import QState
	from QStateMachine import QStateMachine
	from QSystemSemaphore import QSystemSemaphore
	from QTemporaryFile import QTemporaryFile
	from QTextBoundaryFinder import QTextBoundaryFinder
	from QTextCodec import QTextCodec
	from QTextDecoder import QTextDecoder
	from QTextEncoder import QTextEncoder
	from QTextStream import QTextStream
	from QTextStreamManipulator import QTextStreamManipulator
	from QThread import QThread
	from QThreadPool import QThreadPool
	from QTime import QTime
	from QTimeLine import QTimeLine
	from QTimer import QTimer
	from QTimerEvent import QTimerEvent
	from QTranslator import QTranslator
	from QUrl import QUrl
	from QUuid import QUuid
	from QVariantAnimation import QVariantAnimation
	from QWaitCondition import QWaitCondition
	from QWriteLocker import QWriteLocker
	from QXmlStreamAttribute import QXmlStreamAttribute
	from QXmlStreamAttributes import QXmlStreamAttributes
	from QXmlStreamEntityDeclaration import QXmlStreamEntityDeclaration
	from QXmlStreamNamespaceDeclaration import QXmlStreamNamespaceDeclaration
	from QXmlStreamNotationDeclaration import QXmlStreamNotationDeclaration
	from QXmlStreamReader import QXmlStreamReader
	from QXmlStreamWriter import QXmlStreamWriter
except:
	pass